"""empty message

Revision ID: ca40744a2d6f
Revises: 
Create Date: 2024-04-15 14:32:33.872862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca40744a2d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('license_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('license_no'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.owner_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('violation',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('violation_date', sa.String(length=80), nullable=False),
    sa.Column('violation_type', sa.String(length=200), nullable=False),
    sa.Column('violation_status', sa.String(length=80), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('violation_id'),
    sa.UniqueConstraint('violation_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('violation')
    op.drop_table('vehicle')
    op.drop_table('owner')
    # ### end Alembic commands ###
